### ISSUE TITLE
Incompatible with Obfuscate (code library for MrCrayfish vehicle/gun mods)

### ISSUE THREAD

**Issue by UsernameIsTakenAlready** [rejahtavi/rfp2#10]
**Versions**
Minecraft = 1.12.2
Forge = 14.23.5.2838
RFP2 =1.2

**Does the bug happen when only RFP2 is installed?**
NO

**If the above was NO:**
Obfuscate causes this, which is a dependency for MrCrayfish vehicle and gun mods. It's likely that any other gun or vehicle mods cause this as well.

**Describe the bug**
Looking down results in the camera being inside of the player's head and cannot see.

**How To Reproduce**
Install this and MrCrayfish's mods together or just the basic core mod that they all require, Obfuscate.

**Expected behavior**
The head should be invisible to the client while in first person mode.

**Screenshots**
I didn't have time but it's pretty straightforward. You're inside of your head and can't see anything but your face.

**Comment by UsernameIsTakenAlready** [comment]
mods
ambientsounds
B3M
betterfoliage
chopdown
codechickenlib
cofhcore
cofhworld
coralreef
coroutil
corpse
crudestart
davincisvessels
doggytalents
dynamicsurroundings
exhaustedstamina
exoticbirds
eyesinthedarkness
farseek
forgelin
voxelmap
mrcrayfish furniture, guns, vehicles
grappling hook
hardcore darkness
hwyla
immersive engineering
inventory tweaks
jei
justafewfish
millenaire
movingworld
obfuscate <--- cause
optifine
orelib
painting selector
peaceful crafting
your mod
redstoneflux
reforged
repose
shouldersurfing
sound physics
streams
thermaldynamics
thermalexpansion
thermalfoundation
toughasnails
travellersbackpack
weather2
worleycaves

**Comment by rejahtavi** [comment]
This is due to a known incompatibility with the Obfuscate library.
Both mods attempt to override the way that player rendering is handled in first person. Unfortunately, Obfuscate is closed source so I cannot dig deeper to find out why this is happening and design a fix.
Additionally, any fix I might stumble across could easily break rapidly, because Obfuscate is in very early development.

Therefore, I will not be fixing this for the time being.

You should still be able to bind hotkeys and toggle RFP2 manually if you wish to continue to use both mods, you just will not be able to have the 1st person effect when using an obfuscate mod item. Apologies for the inconvenience.

**Comment by rejahtavi** [comment]
Hmm, looks like even with RFP2 loading after obfuscate it still has the rendering issue. I will add a detection to completely disable the mod when obfuscate is loaded.
