### ISSUE TITLE
Bug with shield

### ISSUE THREAD

**Issue by DrBoneYTB** [rejahtavi/rfp2#14]
**Versions**
Minecraft = **1.12.2**
Forge = **release 1.12.2-forge1.12.2-14.23.5.2838**
RFP2 =**RealFirstPerson2-1.12.2-1.2.2**

**Does the bug happen when only RFP2 is installed?**
### YES

**If the above was NO:**
Please try to narrow down which of your other mods is conflicting. Go through and disable a few at a time and test for the bug in a test world. Which mod(s) seem to be related to the issue?

**Describe the bug**
### When I take a shield, the basic minecraft arm appears and the mod arms disappear. 
**How To Reproduce**
A clear and concise description of how to make the bug happen, or if that is unknown, a list of common factors between times that the bug has occurred.
### Just take a shield in your hands.
**Expected behavior**

**Screenshots**
https://gph.is/g/ajyVLWB

**Comment by rejahtavi** [comment]
This is intended behavior. Shields tend to block a lot of the screen with RFP2 enabled, so I disable the mod by default when you are holding a shield.

If you want to bypass this check, you can configure the mod as follows:

1. Open mod options from the pause menu.
2. Select Real First Person 2 and hit Config.
3. Click on "Compatibility"
4. Click on the "Held Item Conflicts" button.
5. Click the [X] next to "minecraft:shield" (and if using thermal expansion, thermalfoundation:shield_*)

You can add and remove items to this list to control which items disable RFP2 when you hold them.

Hope this helps!

**Comment by rejahtavi** [comment]
Forgot to mention -- the compass and the map definitely have to stay on that list, RFP2 view completely breaks their functionality since it uses the 3rd person renderer to achieve the "body in first person" effect -- you will only see your hand holding the "item" representation, as if you were looking at another character holding one of those objects. Don't remove those from the list, and don't expect RFP2 to work while holding a map or compass! Hopefully that clears things up a bit. :)
