### ISSUE TITLE
Help with guns(flans mod)

### ISSUE THREAD

**Issue by xxdi55xx** [rejahtavi/rfp2#16]
i think you could add an option to make things better:
if something has 3d model it will play animation of bow(configurable what would be not)
i am writing this cause i have 5 flans mods and i dont want to spend my life on making a config file

**Comment by rejahtavi** [comment]
Unfortunately there is no simple, universal way for me to tell "if something has a 3d model", because each other mod can implement rendering of their mod's objects in their own way. Many mod packs add 3D models to vanilla items that you _wouldn't_ want this behavior with; the config file option is the best way to allow users to make RFP2 work with the widest variety of mods.

Note that when configuring RFP2, the fields are regexes and you should be able to do something like flansmod:.* to disable it for ALL of the flan's mod items quickly.

(I apologize for the delay in getting back to you, I had several months of chaos in my personal life and simply didn't have the energy to touch minecraft modding.)

Thanks,

Rejah
