### ISSUE TITLE
No compatibility, mod turn off it self...

### ISSUE THREAD

**Issue by shoverno2** [rejahtavi/rfp2#17]
Well, i using more player models with this mod, and...
It's, well, fine.
But newest version can't work together. Maybe you should to add little config about this feature?

**Comment by ThePoshTux** [comment]
I don't see any issue with more player models, I think the blacklist should only be used for mods that are outright incompatible (fail to launch) or are game-breaking (completely impossible to play). Having either hair or a hat from the 3d head layer seems expected from a first-person render. Regardless the mod shouldn't have to disable itself when there are incompatible mods, forge supports listing incompatible mods at run time.

**Comment by rejahtavi** [comment]
Apologies for the delayed response, I've had a long string of personal life chaos that forced me into a pretty big hiatus on coding. I am actively developing RPF2 again, and as such I will be reevaluating all of the conflict reports and seeing if the situation has changed with any of them.

MPM support is not planned for the first update, v1.3.0, but may come later. 1.3.0 is going to include a switch so that you can turn off the blacklist check at your discretion. I do not officially support that configuration but it is your game and absolutely your right to turn off that check. I should have had the toggle in the earlier release -- unfortunately it took me a while to get back to it.

Thanks for the feedback and patience and I will update this thread once i've had a chance to look in to MPM again.

-- Rejah <3

**Comment by rejahtavi** [comment]
"Fixed" in v1.3.1 -- let me explain:

The mod blacklist now presents a warning and disables RFP2 at startup -- but it can be switched on via the hotkey, and the startup alert can be disabled entirely after you've seen it once.

There **are** some visual glitches in some of MPM's animations, but it's all pretty minor compared to how it used to be. I've left MPM on the warnings list as a result of these visual issues, however you are welcome to switch off the warning going forward.
