### ISSUE TITLE
Incompatibility with Pollution of the Realms

### ISSUE THREAD

**Issue by KarlosWGeek** [rejahtavi/rfp2#24]
**Versions**
Minecraft = 1.12.2
Forge = 14.23.5.2847
RFP2 = 1.12.2-1.2.3

**Does the bug happen when only RFP2 is installed?**
No.

**If the above was NO:**
Please try to narrow down which of your other mods is conflicting. Go through and disable a few at a time and test for the bug in a test world. Which mod(s) seem to be related to the issue?

Pollution of the Realms is the conflicting mod.

**Describe the bug**
Pollution of the Realms adds three pieces of armor that are not rendered correctly in First and Third Person when RFP2 is installed. Without RFP2 installed, there are no problems, so the mods are incompatible, even though all functions of the armor pieces still work and there are no crashes (only graphical bug).

**How To Reproduce**
Install Forge, Pollution of the Realms and RFP2. Enter a test world and wear either the Iron, Golden or Diamond Vaccum Bag in the chestplate slot. None of the three will stick to the player's model, they will stay at one position and never move. This issue does not happen without RFP2 installed.

**Expected behavior**
I expected the Vaccum Bags to stick to the player's model, like any chestplate does.

**Screenshots**

https://imgur.com/qyYrORP
https://imgur.com/Y7wL73P
https://imgur.com/LZT0zBK
https://imgur.com/vGkR0nq
https://imgur.com/xazgCIp
https://imgur.com/ykBXUwB
https://imgur.com/orLN2RK

**Comment by rejahtavi** [comment]
Thanks for the feedback. I just got back from a pretty long hiatus and am actively developing RFP2 again. A new version will be coming out soon (v1.3.0) that is mainly refactoring and preparing to add more fixes for mod compatibility just like this.

The 1.3.0 release will not have the fix for this in it, but future version might depending on what I find once I look into PotR's source and/or contact its developers.

I will update this thread once I have had a chance to look in to it.

Thank you for your patience,

-- Rejah <3

**Comment by rejahtavi** [comment]
This ended up actually being an issue with Baubles, since these items from POTR use baubles slots, and not the vanilla player inventory slots.

Good news: Baubles support has been added for beta v1.3.2!

Try it out and let me know how it goes!

Thank you,
-- Rejah <3

**Comment by KarlosWGeek** [comment]
Can confirm fix. Thank you for the quick response!
