### ISSUE TITLE
When Holding a bow or a Shield The Hands Of The first Person view like dosnt show anymore but when u take the shield off It Goes back to normal

### ISSUE THREAD

**Issue by MineShafter1** [rejahtavi/rfp2#34]
An if u are Wondering im using Version 1.12.2.
![20200413_022218](https://user-images.githubusercontent.com/63577082/79097489-e8be3000-7d2d-11ea-96b5-351b35e227fb.jpg)
![20200413_022209](https://user-images.githubusercontent.com/63577082/79097510-f4a9f200-7d2d-11ea-8f24-1a87b6ef3752.jpg)
![20200413_022151](https://user-images.githubusercontent.com/63577082/79097522-fa9fd300-7d2d-11ea-9334-2624c6380973.jpg)

**Comment by rejahtavi** [comment]
This is intentional behavior. You can disable it in the config by looking at the conflict held item lists.

However, if you turn it off, you will get clipping with the shield and it will block a lot of your view -- that's why it is implemented this way. You can also configure it to hide your arms when holding *any* items, or turn off the first person hands entirely if that would make things less jarring for you.
