### ISSUE TITLE
Morph mod compatibility?

### ISSUE THREAD

**Issue by SimulatorSia** [rejahtavi/rfp2#4]
I'm not saying if it is compatible with Morph, I'm asking if it could have compatibility with Morph. If it's way too much work to make it compatible I suggest a line of code that disables your mod's view when a morph is activated maybe?

**Comment by rejahtavi** [comment]
Like some of the other issues opened so far, this will involve adding an optional dependency on Morph and detecting when it is active so that RFP2 can shut itself off on the right frames. You're absolutely correct in that I probably won't be able to give a first person view to morph, but I should be able to get the mod to stop applying any view changes while morph is active. I haven't done any cross-compatibility checks between mods before so this is going to be a little bit of a challenge for me when I work on RFP2 some more in a few weeks. (I'm currently finishing up a private custom mod pack to introduce some friends to modded MC.)

I'll add morph to my list of compatibility goals. Until then, hopefully the new hotkeys help! By default apostrophe toggles the whole mod on demand.

Thank you for the feedback!

**Comment by rejahtavi** [comment]
Morph mod compatibility will be in for 1.2.2, which I will be uploading later this weekend. Keep an eye on curseforge for it :)

**Comment by DD12-1916** [comment]
Just a quick question, if iChun were to agree to have support on their end, would it be possible? I meant with the models being visible in first person
