### ISSUE TITLE
Camera Problem

### ISSUE THREAD

**Issue by TheTwitcher1973** [rejahtavi/rfp2#7]
So when I first found out about this mod, I was excited, I installed the mod onto Minecraft 1.12.2 forge and went into a world.
But for some reason, when i look down, The camera isn't in the right place because I just go through my head and can not see anything.

Any ideas?

Thank You

**Comment by rejahtavi** [comment]
What other mods do you have installed?

**Comment by Team8464** [comment]
TheTwitcher1973 i have the same problem.

**Comment by rejahtavi** [comment]
I will need more information to solve this issue. Please provide:

- your mod list, including versions (you can get this from the log files inside your Minecraft directory)
- a screenshot of the problem occurring

Thank you!

**Comment by Team8464** [comment]
i know the mod it is Obfuscate

**Comment by Phorcis** [comment]
I found another incompatible mod with the same problem - **JJ Races v1.0.7** [1.12.2]

**Comment by rejahtavi** [comment]
This is due to a known incompatibility with the Obfuscate library.
Both mods attempt to override the way that player rendering is handled in first person. Unfortunately, Obfuscate is closed source so I cannot dig deeper to find out why this is happening and design a fix.
Additionally, any fix I might stumble across could easily break rapidly, because Obfuscate is in very early development.

Therefore, I will not be fixing this for the time being.

You should still be able to bind hotkeys and toggle RFP2 manually if you wish to continue to use both mods, you just will not be able to have the 1st person effect when using an obfuscate mod item. Apologies for the inconvenience.

**Comment by rejahtavi** [comment]
Hmm, looks like even with RFP2 loading after obfuscate it still has the rendering issue. I will add a detection to completely disable the mod when obfuscate is loaded.
